version: "3.9"

services:
  db:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=quote_gallery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  web:
    image: schokotets/quote_gallery
    build: .
    ports:
      - "80:80"
    environment:
      - DB_USER=postgres
      - DB_PWD=1234
      - DB_NAME=quote_gallery
      - DB_SSLMODE=disable

volumes:
  db-data:
